# Generated by Django 5.2.6 on 2025-09-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertenantmodel',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='usertenantmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
